import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import Hero from '../components/Hero/Hero';

const Wrapper = styled.div`
  background: #082543;
`;

const Container = styled.div`
  padding: 4rem;
  min-height: 100vh;
  max-width: 1240px;
  margin: 0 auto;
`;

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <Hero />
      </Container>
    </Wrapper>
  );
};

export default Home;
