import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import Card from '../components/Card';
import Header from '../components/Header';
import Hero from '../components/Hero/Hero';
import Submit from '../components/Submit/Submit';
import FooterComp from '../components/Footer';

const Wrapper = styled.section`
  position: relative;
  /* background: #082543; */
`;

const Background = styled.div`
  width: 100%;
  height: 100%;
  position: absolute;
  background: url('https://lps.cognni.ai/hubfs/Gradient-Background-JUL14-1.png');
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
  top: -600px;
  z-index: -1;
`;

const Container = styled.section`
  padding: 2rem 2rem 5.5rem 2rem;
  /* min-height: 100vh; */
  max-width: 1240px;
  margin-bottom: 15rem;
  margin: 0 auto;
  @media (min-width: 50em) {
    margin-bottom: 25rem;
  }
`;

const HeroWrapper = styled.section`
  display: grid;
  align-items: center;
  gap: 4rem;
  margin-top: 116px;
  @media (min-width: 56em) {
    grid-template-columns: 1fr 1fr;
  }
`;

const Home: NextPage = () => {
  return (
    <>
      <Header />
      <main>
        <Wrapper>
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Background />
          <Container>
            <HeroWrapper>
              <Hero />
              <Submit />
            </HeroWrapper>
          </Container>
          <Card />
        </Wrapper>
        <FooterComp />
      </main>
    </>
  );
};

export default Home;
